import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import useSWR from 'swr'
import PieCard from '../../components/PieCard'
import VerticalBarCard from '../../components/VerticalBarCard'
import { IAnime } from '../../models/Anime'
import fetcher from '../../utils/fetcher'
import styles from '../../styles/Stats.module.scss'
import { mostWatchedGenres, animeCountByYear } from '../../utils/statistics'

const Stats: NextPage = () => {
    const router = useRouter();
    const username = router.query.stats;
    const { data: animeList, error } = useSWR<IAnime[]>(`/api/stats/${username}`, fetcher)

    if (error) {
        console.error(error);
    }

    const mostWatchedGenresArr = mostWatchedGenres(animeList);
    const animeCountByYearArr = animeCountByYear(animeList);
    console.log(animeCountByYearArr)
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <section className='hero'>
                    <div className='hero-body'>
                        <div className='container'>
                            <div className='columns'>
                                <div className='column is-half'>
                                    <PieCard title={'Most Watched Genres'}
                                        labels={mostWatchedGenresArr?.[0]}
                                        fillData={mostWatchedGenresArr?.[1]} />
                                </div>
                                <div className='column is-half'>
                                    <VerticalBarCard title={'Anime By Release Year'}
                                        labels={animeCountByYearArr?.[0]}
                                        fillData={animeCountByYearArr?.[1]} />
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </main>

            <footer className={`footer ${styles.footer}`}>
                <div className="content has-text-centered">
                    <p className='has-text-white'>
                        <strong className='has-text-white'>AnimeStats</strong> can be found <a className={`${styles.footeranchor}`} href="https://github.com/bernasx">here.</a>
                    </p>
                </div>
            </footer>
        </div>
    )
}



export default Stats
